### ISSUE TITLE
https://github.com/wildbohana/cs_oot/blob/main/v05/xaml.txt

### ISSUE THREAD

**Issue by owlCoder** [wildbohana/cs_oot#1]
конкретно за лабелу
главна разлика између текст бокса и лабеле су атрибути тј текстбокс искључиво може да има текст и ништа више, док лабела у себи може садржати и текст и слику (рисрч лаб: развуци лабелу преко целог прозора, пошаљи позади и подеси јој садржај на неку кул позадину).

**Comment by wildbohana** [comment]
истражила сам ја лабелу и видела сам какве су разлике, него сам ово писала конкретно за елементе који нам требају за К2

**Comment by owlCoder** [comment]
Vaš istraživački rad biće mali korak za nas, ali veliki za čovečanstvo!

**Comment by wildbohana** [comment]
queen slaaayyyy
